shop/config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :shop_admins
  resources :shops
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

shop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shop/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :shop
end

shop/app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_admins
  has_many :items
end

shop/app/models/shop_admin.rb
class ShopAdmin < ApplicationRecord
  belongs_to :shop
end

shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

shop/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:itemCatagory, :picPath, :videoPath, :detail, :price, :shop_id)
    end
end

shop/app/controllers/shop_admins_controller.rb
class ShopAdminsController < ApplicationController
  before_action :set_shop_admin, only: [:show, :edit, :update, :destroy]

  # GET /shop_admins
  # GET /shop_admins.json
  def index
    @shop_admins = ShopAdmin.all
  end

  # GET /shop_admins/1
  # GET /shop_admins/1.json
  def show
  end

  # GET /shop_admins/new
  def new
    @shop_admin = ShopAdmin.new
  end

  # GET /shop_admins/1/edit
  def edit
  end

  # POST /shop_admins
  # POST /shop_admins.json
  def create
    @shop_admin = ShopAdmin.new(shop_admin_params)

    respond_to do |format|
      if @shop_admin.save
        format.html { redirect_to @shop_admin, notice: 'Shop admin was successfully created.' }
        format.json { render :show, status: :created, location: @shop_admin }
      else
        format.html { render :new }
        format.json { render json: @shop_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_admins/1
  # PATCH/PUT /shop_admins/1.json
  def update
    respond_to do |format|
      if @shop_admin.update(shop_admin_params)
        format.html { redirect_to @shop_admin, notice: 'Shop admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop_admin }
      else
        format.html { render :edit }
        format.json { render json: @shop_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_admins/1
  # DELETE /shop_admins/1.json
  def destroy
    @shop_admin.destroy
    respond_to do |format|
      format.html { redirect_to shop_admins_url, notice: 'Shop admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_admin
      @shop_admin = ShopAdmin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_admin_params
      params.require(:shop_admin).permit(:fname, :lname, :email, :password, :owns_id)
    end
end

shop/app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:catagory, :name, :detail, :location)
    end
end

shop/app/helpers/application_helper.rb
module ApplicationHelper
end

shop/app/helpers/items_helper.rb
module ItemsHelper
end

shop/app/helpers/shop_admins_helper.rb
module ShopAdminsHelper
end

shop/app/helpers/shops_helper.rb
module ShopsHelper
end

shop/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :itemCatagory %>
    <%= form.text_field :itemCatagory %>
  </div>

  <div class="field">
    <%= form.label :picPath %>
    <%= form.text_field :picPath %>
  </div>

  <div class="field">
    <%= form.label :videoPath %>
    <%= form.text_field :videoPath %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.text_field :shop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

shop/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

shop/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Itemcatagory</th>
      <th>Picpath</th>
      <th>Videopath</th>
      <th>Detail</th>
      <th>Price</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.itemCatagory %></td>
        <td><%= item.picPath %></td>
        <td><%= item.videoPath %></td>
        <td><%= item.detail %></td>
        <td><%= item.price %></td>
        <td><%= item.shop_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

shop/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

shop/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Itemcatagory:</strong>
  <%= @item.itemCatagory %>
</p>

<p>
  <strong>Picpath:</strong>
  <%= @item.picPath %>
</p>

<p>
  <strong>Videopath:</strong>
  <%= @item.videoPath %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @item.detail %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @item.shop_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopEyob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

shop/app/views/shop_admins/_form.html.erb
<%= form_with(model: shop_admin, local: true) do |form| %>
  <% if shop_admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop_admin.errors.count, "error") %> prohibited this shop_admin from being saved:</h2>

      <ul>
        <% shop_admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fname %>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :owns_id %>
    <%= form.text_field :owns_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

shop/app/views/shop_admins/edit.html.erb
<h1>Editing Shop Admin</h1>

<%= render 'form', shop_admin: @shop_admin %>

<%= link_to 'Show', @shop_admin %> |
<%= link_to 'Back', shop_admins_path %>

shop/app/views/shop_admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shop Admins</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Password</th>
      <th>Owns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shop_admins.each do |shop_admin| %>
      <tr>
        <td><%= shop_admin.fname %></td>
        <td><%= shop_admin.lname %></td>
        <td><%= shop_admin.email %></td>
        <td><%= shop_admin.password %></td>
        <td><%= shop_admin.owns_id %></td>
        <td><%= link_to 'Show', shop_admin %></td>
        <td><%= link_to 'Edit', edit_shop_admin_path(shop_admin) %></td>
        <td><%= link_to 'Destroy', shop_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop Admin', new_shop_admin_path %>

shop/app/views/shop_admins/new.html.erb
<h1>New Shop Admin</h1>

<%= render 'form', shop_admin: @shop_admin %>

<%= link_to 'Back', shop_admins_path %>

shop/app/views/shop_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @shop_admin.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @shop_admin.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @shop_admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @shop_admin.password %>
</p>

<p>
  <strong>Owns:</strong>
  <%= @shop_admin.owns_id %>
</p>

<%= link_to 'Edit', edit_shop_admin_path(@shop_admin) %> |
<%= link_to 'Back', shop_admins_path %>

shop/app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :catagory %>
    <%= form.text_field :catagory %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

shop/app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

shop/app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Detail</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.type %></td>
        <td><%= shop.name %></td>
        <td><%= shop.detail %></td>
        <td><%= shop.location %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

shop/app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

shop/app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @shop.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @shop.detail %>
</p>

<p>
  <strong>Location:</strong>
  <%= @shop.location %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>